apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: claude-warroom

resources:
  - ../base
  - job-template.yaml

configMapGenerator:
  - name: claude-prompts
    files:
      - control-plane-health.md=../prompts/control-plane-health.md
      - api-unreachable.md=../prompts/api-unreachable.md
      - nodes-not-joining.md=../prompts/nodes-not-joining.md
      - nodes-not-ready.md=../prompts/nodes-not-ready.md
      - etcd-performance.md=../prompts/etcd-performance.md
      - pod-scheduling-failures.md=../prompts/pod-scheduling-failures.md
      - operator-degraded.md=../prompts/operator-degraded.md
      - network-connectivity.md=../prompts/network-connectivity.md
      - cluster-upgrade-stuck.md=../prompts/cluster-upgrade-stuck.md
      - hosted-cluster-partial.md=../prompts/hosted-cluster-partial.md
      - comprehensive-dump.md=../prompts/comprehensive-dump.md
      - control-plane-restart.md=../prompts/control-plane-restart.md
      - pause-reconciliation.md=../prompts/pause-reconciliation.md
      - scale-nodepool.md=../prompts/scale-nodepool.md
  
  - name: claude-context
    files:
      - CLAUDE.md=../../CLAUDE.md
      - strategy.md=../../hypershift-troubleshooting-strategy.md

# Replace Job name with timestamp to ensure uniqueness
replacements:
  - source:
      kind: ConfigMap
      name: claude-prompts
      fieldPath: metadata.annotations.configMapVersion
    targets:
      - select:
          kind: Job
        fieldPaths:
          - spec.template.metadata.annotations.[configmap/version]